"""Create Students table

Revision ID: 69c3bb1845fa
Revises: c64cc49c84d2
Create Date: 2023-10-06 09:14:18.821360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c3bb1845fa'
down_revision = 'c64cc49c84d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('idnumber', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('laptop_model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('tm_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
